### ISSUE TITLE
Alert file needs basic functionality

### ISSUE THREAD

**Issue by latran** [RedHatQE/widgetastic.patternfly4#133]
Like it's previous version, the alert file need basic functionality like `dismiss` and `accept` to provide more flexibility whenever an alert appears on a particular page.  As of now, the alerts are blocking buttons on certain pages and there needs to be a `dismiss` function so the rest of automation can proceed.  We have a lot of failures because of this.

The ask is moving https://github.com/RedHatQE/widgetastic.patternfly/pull/92 functionality to PF4.

**Comment by quarckster** [comment]
@latran As far as I know Patternfly alerts have only a close button http://patternfly-react.surge.sh/components/alert. It's located within `<div class="pf-c-alert__action">...</div>. `Alert` has a `click_action` method https://github.com/RedHatQE/widgetastic.patternfly4/blob/master/src/widgetastic_patternfly4/alert.py#L45 that clicks on the close button. Try use it in your tests.

**Comment by mshriver** [comment]
@latran I think the problem we're seeing is related to Satellite (Foreman) specifically, not WT.PF4.  The component in use is a modal, not a PF4 alert.

The confirmation dialog that we're hitting is defined completely within airgun:
https://github.com/SatelliteQE/airgun/blob/eed927e3f2b4a9f90bcc008670e5a88de1f2fa80/airgun/widgets.py#L1022

This modal is not recognized as a JS alert, so the WT.core `handle_alert` and `get_alert` functions don't identify the component.

This needs to be addressed with the foreman UX team - if they can't modify the modal DOM so that its recognized as a JS alert, then we need to override `get_alert` in airgun's browser class to find the confirmation modal.
